intaro_api:
    type: rest
    resource: Intaro\ApiBundle\Controller\BookController
    prefix:   /api/v1/

intaro_book:
    resource: "@IntaroBookBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

