intaro_api:
    resource: "@IntaroApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1

intaro_book:
    resource: "@IntaroBookBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

