parameters:
#    intaro_book.example.class: Intaro\BookBundle\Example

services:
    intaro_book.file_remover:
        class: Intaro\BookBundle\Subscriber\BookFileRemover
        tags:
            - { name: doctrine.event_listener, event: postRemove }
